// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, created_at, updated_at, type, color, brand, material, category)
VALUES (
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, color, type, brand, material, category
`

type CreateItemParams struct {
	Type     string
	Color    sql.NullString
	Brand    sql.NullString
	Material sql.NullString
	Category sql.NullString
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Type,
		arg.Color,
		arg.Brand,
		arg.Material,
		arg.Category,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Type,
		&i.Brand,
		&i.Material,
		&i.Category,
	)
	return i, err
}

const deleteItems = `-- name: DeleteItems :exec
DELETE FROM items
`

func (q *Queries) DeleteItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteItems)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, created_at, updated_at, color, type, brand, material, category
FROM items
WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Type,
		&i.Brand,
		&i.Material,
		&i.Category,
	)
	return i, err
}

const getItems = `-- name: GetItems :many
SELECT id, created_at, updated_at, color, type, brand, material, category FROM items
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Color,
			&i.Type,
			&i.Brand,
			&i.Material,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET
    updated_at = now(),
    type = COALESCE($2, type),
    color = COALESCE($3, color),
    brand = COALESCE($4, brand),
    material = COALESCE($5, material),
    category = COALESCE($6, category)
WHERE id = $1
RETURNING id, created_at, updated_at, color, type, brand, material, category
`

type UpdateItemParams struct {
	ID       uuid.UUID
	Type     string
	Color    sql.NullString
	Brand    sql.NullString
	Material sql.NullString
	Category sql.NullString
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.ID,
		arg.Type,
		arg.Color,
		arg.Brand,
		arg.Material,
		arg.Category,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Type,
		&i.Brand,
		&i.Material,
		&i.Category,
	)
	return i, err
}
