// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"database/sql"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, created_at, updated_at, color, type)
VALUES (
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, color, type
`

type CreateItemParams struct {
	Color sql.NullString
	Type  string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.Color, arg.Type)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
		&i.Type,
	)
	return i, err
}

const deleteItems = `-- name: DeleteItems :exec
DELETE FROM items
`

func (q *Queries) DeleteItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteItems)
	return err
}
