// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Color     string
	Type      string
}
